### ISSUE TITLE
Request support for CallExpression node type

### ISSUE THREAD

**Issue by JohnArrowwood** [donmccurdy/expression-eval#1]
I'm creating an application that lets me declare variables and assign them expressions.  I'd like to be able to support expressions like `random.int(min,max)` or `random.guid()` and have it evaluate as you might expect.  

Unfortunately, the evaluation engine ignores nodes of type CallExpression.

Is there any reason why it would be a bad idea for me to initialize certain names to functions so that they can be used in an expression?

**Comment by donmccurdy** [comment]
This would be a nice addition, agreed. I’d be glad to take a PR adding CallExpression to the `evaluate` function here: https://github.com/donmccurdy/expression-eval/blob/master/index.js

**Comment by donmccurdy** [comment]
Fixed via #4, thanks!
