### ISSUE TITLE
Fast eval

### ISSUE THREAD

**Issue by ubreddy** [donmccurdy/expression-eval#19]
When there are || conditions, can we have the evaluation not evaluate the right side of || if left is already true?

**Comment by donmccurdy** [comment]
Fixed at https://github.com/donmccurdy/expression-eval/pull/20, will push to NPM in a day or two.

**Comment by donmccurdy** [comment]
I think this code needed to go under `LogicalExpression` actually, see https://github.com/donmccurdy/expression-eval/commit/d04f42d79cc25a80c6c4852dd66ab43ba7b011d4. Can you confirm? If it's under BinaryExpression instead for some reason, another test case would be helpful. :)

**Comment by ubreddy** [comment]
Yes. But would suggest to keep it at both places.

**Comment by donmccurdy** [comment]
I've published this as 1.4.0 on npm — based on the [jsep code here](https://github.com/soney/jsep/blob/master/src/jsep.js#L92) I believe it will always be a LogicalExpression, so unless there's an example of the other and we can write a unit test to cover it, I'll just include that for now.
