### ISSUE TITLE
Could context be a function?

### ISSUE THREAD

**Issue by iskandersierra** [donmccurdy/expression-eval#21]
In line (https://github.com/donmccurdy/expression-eval/blob/master/index.js#L80), when is time to evaluate an identifier, the context is assumed to be a hash (object). It would be useful to give as an option that context could be a function:
```
expr.eval(ast, function(identifier) {
    // here use whatever strategy to evaluate identifier
})
```
I can make the tests and PR if you like.

**Comment by iskandersierra** [comment]
Well, line 80 anf 97 are th only places that whould be necesary to change. The ```this``` expression would not make sense if it would return the context function. Maybe in that case we could call ```context('this')``` as an special case.
But basically the change in line 80 would be (untested):
```javascript
if (typeof context === 'function') {
  return context(node.name)
} else {
  return context[node.name] // current implementation
}
```
In line 97 would be the same but using ```'this'``` as a parameter to context instead of ```node.name```

It would be helpful to have some unit tests in place to ensure nothing no presupositions break. But thats for another time.

**Comment by donmccurdy** [comment]
Sounds good to me if you'd like to do a PR.

> Maybe in that case we could call `context('this')` as an special case.

Let's just return `undefined` here I think.
