### ISSUE TITLE
How to call async functions in an expression?

### ISSUE THREAD

**Issue by hsluoyz** [donmccurdy/expression-eval#22]
Thanks for this good project! In my scenario, I need to put async functions into expression. But I don't know how to do this. It seems that jsep doesn't support sync functions?

The following code generates async functions which will be injected into the expression:

https://github.com/casbin/node-casbin/blob/e40a13ffd8fbb2d924f36541beb24b3a02593261/src/util/builtinOperators.ts#L138-L153

The following code shows how the above async functions are injected:

https://github.com/casbin/node-casbin/blob/504047efd9317550e223680a4a81dc046fe63848/src/coreEnforcer.ts#L253-L311

**Comment by donmccurdy** [comment]
New version will be published soon.

**Comment by hsluoyz** [comment]
@dreamdevil00 please ping me when new version is released :)

**Comment by donmccurdy** [comment]
v2.0.0 is on NPM now: https://www.npmjs.com/package/expression-eval.
