### ISSUE TITLE
Doesnt work change filename

### ISSUE THREAD

**Issue by malynytsky** [donmccurdy/expression-eval#25]
Hello, 

I try use on firefox change to ${index-1} - ${name}${ext}, and images downloaded with name like this:
undefined - EmbeddedRelated_smalltab.jpg

How i can fix, to change start from 0, or something else number?

0 - EmbeddedRelated_smalltab.jpg
100 - EmbeddedRelated_smalltab.jpg

Sorry for my pure english.

**Comment by donmccurdy** [comment]
I don't know what you're asking, sorry... how are you using the expression-eval library here?
