### ISSUE TITLE
Eval collision in examples

### ISSUE THREAD

**Issue by josh-hemphill** [donmccurdy/expression-eval#33]
In the change to the readme 28feab589f332b929e22b819651e62b358dceed3 you show destructuring the functions instead of leaving it in an object. This would cause expression-eval `eval()` to replace the native `eval()`.

**Comment by donmccurdy** [comment]
Yes. Aliasing it to another name would also be fine, but I don't think it's necessary to explain JavaScript scope in the documentation.
