### ISSUE TITLE
What changed between v2 & v3?

### ISSUE THREAD

**Issue by josh-hemphill** [donmccurdy/expression-eval#36]
I didn't see any comments in the releases. Where there breaking changes for moving from [v2.1](https://github.com/donmccurdy/expression-eval/releases/tag/v2.1.0) to [v3.1](https://github.com/donmccurdy/expression-eval/releases/tag/v3.1.0)?

**Comment by donmccurdy** [comment]
I considered the build process changes and updating to [ES modules](https://github.com/donmccurdy/expression-eval/commit/e092a20796308e3494101eb41314db09ea9ddf91) to be at risk of creating a breaking change. It may not actually have broken anything, but doesn't hurt to be safe.
