### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by redjacket87** [donmccurdy/expression-eval#43]
const ast = parse('object.id === 1');
const context = {object: null};// 
console.log( eval(ast, context)); // Error: cannot read property

Some fields in context may be null, because you can form it dynamic. 
Maybe it better use optional-chaining operator in eval method

Thanks

**Comment by donmccurdy** [comment]
Thanks for the suggestion! This project relies on https://github.com/EricSmekens/jsep for expression parsing, which does not (to my understanding) have an optional-chaining operator. It does have support for custom operators (which this project also allows) but I'm not sure an optional-chaining operator is technically a unary or binary operator... you may need to follow up there.
