### ISSUE TITLE
Using addBinaryOp causes some expressions to fail to parse

### ISSUE THREAD

**Issue by skermes** [donmccurdy/expression-eval#45]
The `addBinaryOp` in expression-eval doesn't set the `precedence` parameter when it calls `addBinaryOp` in jsep, which will make some valid expressions raise an exception while parsing. This can be worked around by calling jsep.addBinaryOp as well, but it would be better to not have to do that.

Reproduction:
```
> ee = require('expression-eval')
> ee.parse('(1 + 2 + 3)')           // This returns a valid AST
> ee.addBinaryOp('+', (a, b) => a + b + 1)
> ee.parse('(1 + 2 + 3)')          // This raises an exception about a missing close paren
> ee.parse.addBinaryOp('+', 9)
> ee.parse('(1 + 2 + 3)')          // This returns a valid AST again 
```

Unfortunately from glancing at the jsep source it looks like the binary_ops dictionary is stuck inside a closure so there isn't an easy way to use it as a source of default precedence values.

**Comment by donmccurdy** [comment]
> This can be worked around by calling jsep.addBinaryOp as well, but it would be better to not have to do that.

I'm not sure I understand, we always have to call `jsep.addBinaryOp` here...

https://github.com/donmccurdy/expression-eval/blob/be8c9e22d6c9e32843ec00b0a6dbfaee72c18dfb/index.js#L214-L218

Is this just an issue when overriding an existing operator?

**Comment by skermes** [comment]
No, it happens for any operator. The issue is that `jsep.addBinaryOp` takes two parameters but you're only passing one:
```
jsep.addBinaryOp = function(op_name, precedence) {
	max_binop_len = Math.max(op_name.length, max_binop_len);
	binary_ops[op_name] = precedence;
	return this;
};
```
(https://github.com/EricSmekens/jsep/blob/master/src/jsep.js#L604)

When you only supply the `name` parameter here jsep ends up with an dictionary entry `binary_ops['+'] = undefined`. I haven't dug into the internals of jep enough to know why, but that seems to cause it to fail to parse some strings. The smallest string I've been able to find that it fails on is `(1 + 2 + 3)`, where `+` can be any operator with an undefined precedence:
```
> ee = require('expression-eval')
> ee.addBinaryOp('~', (a, b) => a + b)
> ee.parse('1 ~2')               // This returns a valid AST
> ee.parse('(1 ~ 2 ~ 3)')        // This throws an exception
```
If I call `jsep.addBinaryOp` with both parameters both strings will parse fine:
```
> ee.parse.addBinaryOp('~', 5)
> ee.parse('1 ~ 2')             // Returns a valid AST
> ee.parse('(1 ~ 2 ~ 3)')       // Returns a valid AST
```

**Comment by donmccurdy** [comment]
Ok thanks — it sounds like the `addBinaryOp` method in this library should just take an extra parameter then, would you be able to put in a PR for the fix, and/or a unit test for the issue? I would suggest using an order to match jsep itself...

```
addBinaryOp(op, precedence, fn)
```

... and detecting and handling the previous two-parameter usage for backwards compatibility.
