### ISSUE TITLE
node_modules/expression-eval/dist/index.d.ts(1,8): error TS1259: Module '"jsep"' can only be default-imported using the 'allowSyntheticDefaultImports' flag

### ISSUE THREAD

**Issue by hsluoyz** [donmccurdy/expression-eval#49]
First thanks for this amazing project! Node-Casbin uses expression-eval as the expression evaluator. Our recent GitHub Actions failed owing to a expression-eval issue, can you take a look? Thanks!

https://github.com/casbin/node-casbin/issues/231#issuecomment-768954794

https://github.com/casbin/node-casbin/runs/1783266710?check_suite_focus=true

![image](https://user-images.githubusercontent.com/3787410/106130579-7f17f100-619c-11eb-9d2b-29d8266271c3.png)

**Comment by donmccurdy** [comment]
See:

- https://github.com/donmccurdy/expression-eval/issues/41
- https://github.com/donmccurdy/expression-eval/pull/37

I'm not sure how to fix it, and have tried several things at this point... The root of the problem might be that this library depends on `jsep`, and [`jsep` does not provide ES modules](https://github.com/EricSmekens/jsep/blob/master/src/jsep.js). Enabling `"esModuleInterop": true` in your `tsconfig.json` might also fix the problem. This library compiles fine with TS, so I'm not sure why upstream users of the library (specifically TypeScript builds?) cannot compile. 😕

**Comment by hsluoyz** [comment]
Hi @donmccurdy I found it's caused by the latest expression-eval v4.0.0, if we revert it to v2.0.0, the issue is gone. Thanks!

See details at: https://github.com/casbin/node-casbin/issues/231#issuecomment-769540271
