### ISSUE TITLE
Support optional-chain-like behavior for context objects

### ISSUE THREAD

**Issue by mshick** [donmccurdy/expression-eval#50]
I found the need for accessing deep properties on the context which may be undefined. This module currently will throw when trying to access those properties; a behavior that treats the deep object access similar to an optional chain seemed like a good solution.

Writing this to highlight the PR (https://github.com/donmccurdy/expression-eval/pull/48) I submitted a couple days ago, in the event it was missed, or anybody not checking out the PRs wanted to chime in.

Thanks for the great project here!

**Comment by donmccurdy** [comment]
Hi! There was a similar suggestion in https://github.com/donmccurdy/expression-eval/issues/43. I was hoping that this could be done using custom operators (i.e. defining `?.` in userland) but as far as I can tell that isn't possible, so I'm ok with going ahead and adding as an optional parameter. I've left some comment on your PR — thanks!

**Comment by donmccurdy** [comment]
No current plans of working on this, but willing to revisit with PR feedback addressed. Thanks!
