### ISSUE TITLE
The processing of floating-point numbers failed 

### ISSUE THREAD

**Issue by mwei2018** [donmccurdy/expression-eval#56]
The processing of floating-point numbers failed 
  
console.log('---------tesst');
  const ast4 = parse('a * b +c *9.9');
  const value4 = eval(ast4, {a: 5, b: 2, c: 4.9}); 
  console.log(ast4);
  console.log(value4);

----------------result---------
![image](https://user-images.githubusercontent.com/2967082/120429595-3a010700-c3a8-11eb-96ef-101655412088.png)
How do we ensure that floating-point number calculations are normal digits

**Comment by donmccurdy** [comment]
It is the same result given by JavaScript itself, as this library evaluates expressions without reimplementing language features.

<img width="177" alt="Screen Shot 2021-06-02 at 8 49 54 AM" src="https://user-images.githubusercontent.com/1848368/120502276-225d5a80-c377-11eb-8b27-d85b6203c963.png">

If you'd like to override the default math operators you can do so...

```ts
expr.addBinaryOp('8', (a, b) => {
  let product;
  // ... compute product of A and B with BigDecimal or another math library ...
  return product;
});
```

... but you'd need to use something like BigDecimal to avoid the [usual floating point issues](https://floating-point-gui.de/).
