### ISSUE TITLE
Is it possible to support "in" operator?

### ISSUE THREAD

**Issue by hsluoyz** [donmccurdy/expression-eval#58]
"in" is something like: https://casbin.org/docs/en/syntax-for-models#speical-grammer

```
r.sub.Name in (r.obj.Admins)
```

Is it possible to support it? Thanks!

**Comment by donmccurdy** [comment]
Hi!

This operator isn't included in the library, but you can use the `addBinaryOp` function to create one. For example:

https://github.com/donmccurdy/expression-eval/blob/1b3f601e02acf2867ef0896ba66f876b5746c0f3/test.js#L121
