### ISSUE TITLE
Question: Is there a way to generate an expression from an AST?

### ISSUE THREAD

**Issue by ciukstar** [donmccurdy/expression-eval#64]
Hi!
Is there a way to use ```expression-eval``` to generate the expression from an ```AST```? Unparsing? To perform the reverse of a parse operation?
Thanks!

**Comment by donmccurdy** [comment]
Hey! Just to check - you want to take the AST and reconstruct the expression as a string, correct? There's an issue on the `jsep` repository that looks like it might have a good place to start: https://github.com/EricSmekens/jsep/issues/73

**Comment by ciukstar** [comment]
> Hey! Just to check - you want to take the AST and reconstruct the expression as a string, correct? There's an issue on the `jsep` repository that looks like it might have a good place to start: [EricSmekens/jsep#73](https://github.com/EricSmekens/jsep/issues/73)

Yes. I meant to take the AST and restore the expression as a string.
As I see, it is not implemented. 
Thanks!
