### ISSUE TITLE
Is parse considered safe?

### ISSUE THREAD

**Issue by jcalfee** [donmccurdy/expression-eval#66]
Do you consider parse to be safe enough to run on the server?  The use-case is to run expression-eval parse but not eval before vm2 does parsing and evaluating.  The purpose is to ensure the server-side expressions are only valid if they are valid on the client, and also to help reduce the chance of hitting a security vulnerability in vm2.

**Comment by donmccurdy** [comment]
I've written a bit more under the [*Security*](https://github.com/donmccurdy/expression-eval#security) section in the readme, but in short — it depends. The package does not provide a sandbox, and running user-provided expressions or even values could be a risk.

That said, the `parse` function is just re-exported from [jsep](https://ericsmekens.github.io/jsep/), not implemented by this package. I can't vouch for their code, but would be surprised if just parsing the AST were unsafe.
