### ISSUE TITLE
Wrong results when using exponent symbol (^) in expression

### ISSUE THREAD

**Issue by leoncvlt** [donmccurdy/expression-eval#69]
Hello, I've noticed that the result of my expressions seems wrong when using the exponent symbol (^):

```js
const foo = { a: 1, b: 2, c: 3 };

console.log(evaluate(parse("10 + (2 ^ a)"), foo)); // expected: 12, result: 13
console.log(evaluate(parse("10 + (2 ^ b)"), foo)); // expected: 14, result: 10
console.log(evaluate(parse("10 + (2 ^ c)"), foo)); // expected: 18, result: 11
```

Reproducible codesandbox: https://codesandbox.io/s/expression-eval-exponent-zof7gt?file=/src/index.js:0-350

**Comment by donmccurdy** [comment]
Hi @leoncvlt! The `^` operator is a bitwise XOR, and not an exponent operator, in this library as in JavaScript. If you'd like to override its behavior you can do:

```javascript
import * as Exp from "expression-eval";

Exp.addBinaryOp('^', (a,b) => Math.pow(a,b));
```

**Comment by leoncvlt** [comment]
Ha, that makes sense! Thanks for the explanation.
