### ISSUE TITLE
The expr.eval example in the README doesn't work

### ISSUE THREAD

**Issue by eight04** [donmccurdy/expression-eval#7]
> expr.eval('a + b / c', {a: 2, b: 2, c: 5}); // 0.8

https://github.com/donmccurdy/expression-eval/blob/6611345f35ca61bb28e440693bc568f74a8c66a9/index.js#L102

`evaluate` accept a `node` instead of a string. I'm not sure which is correct.

**Comment by donmccurdy** [comment]
Oops, good catch thanks. The intention is that you would call `parse()` to get an AST/node, then `eval()` to compute a value.
